!classDefinition: #TestTerniLapilli category: #TerniLapilli!
TestCase subclass: #TestTerniLapilli
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TerniLapilli'!

!TestTerniLapilli methodsFor: 'as yet unclassified' stamp: 'rjs 6/11/2020 19:39:58'!
test01StartsGameWithEmptyBoardAndMovesX
! !

!TestTerniLapilli methodsFor: 'as yet unclassified' stamp: 'rjs 6/11/2020 19:40:33'!
test02PlayerXMakesAMove
! !

!TestTerniLapilli methodsFor: 'as yet unclassified' stamp: 'rjs 6/11/2020 19:43:29'!
test03XPlayedNowPlaysO
! !


!classDefinition: #NameOfSubclass category: #TerniLapilli!
Object subclass: #NameOfSubclass
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TerniLapilli'!
