!classDefinition: #CarritoTest category: #TusLibrosDotCom!
TestCase subclass: #CarritoTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TusLibrosDotCom'!

!CarritoTest methodsFor: 'as yet unclassified' stamp: 'rjs 7/2/2020 20:06:35'!
test01EmptyCarritoHasEmptyList! !

!CarritoTest methodsFor: 'as yet unclassified' stamp: 'rjs 7/2/2020 20:09:14'!
test02CarritoCanHaveLibrito! !

!CarritoTest methodsFor: 'as yet unclassified' stamp: 'rjs 7/2/2020 20:09:51'!
test03CarritoCanHaveManyLibritos! !

!CarritoTest methodsFor: 'as yet unclassified' stamp: 'rjs 7/2/2020 20:10:50'!
test04CarritoCanHaveManyOfThisLibrito! !
